crossfit_a6_admin:
    resource: "@CrossfitA6AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

crossfit_a6_front:
    resource: "@CrossfitA6FrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"